# finished 19/06/2025
# https://docs.docker.com/compose/compose-file/
version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: vrm-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:6
    container_name: vrm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: vrm-backend
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - .env # Global (project root)
      - ./backend/.env # Backend-specific
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://vrm-mongo:27017/vrm_db
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # keep the frontend independent for easy development
  # frontend:
  #   build: ./frontend
  #   container_name: vrm-frontend
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #       # condition: service_started
  #   env_file:
  #     - ./frontend/.env
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "3000:80"
  #     - "80:80" # easier for using single frontend with nginx default port
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

volumes:
  mongo_data:
  minio_data:
