exports.mock_users = [
  {
    username: "nhanvien01",
    email: "nhanvien01@example.com",
    password: "mk123@",
    name: "Nhân Viên 01",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0001",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien02",
    email: "nhanvien02@example.com",
    password: "mk123@",
    name: "Nhân Viên 02",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0002",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien03",
    email: "nhanvien03@example.com",
    password: "mk123@",
    name: "Nhân Viên 03",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0003",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien04",
    email: "nhanvien04@example.com",
    password: "mk123@",
    name: "Nhân Viên 04",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0004",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien05",
    email: "nhanvien05@example.com",
    password: "mk123@",
    name: "Nhân Viên 05",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0005",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien06",
    email: "nhanvien06@example.com",
    password: "mk123@",
    name: "Nhân Viên 06",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0006",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien07",
    email: "nhanvien07@example.com",
    password: "mk123@",
    name: "Nhân Viên 07",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0007",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien08",
    email: "nhanvien08@example.com",
    password: "mk123@",
    name: "Nhân Viên 08",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0008",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "truongphong01",
    email: "truongphong01@example.com",
    password: "mk123@",
    name: "Trưởng Phòng 01",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "TP0001",
    roles: ["Trưởng Phòng"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: true, write: true, delete: true },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: true,
  },
  {
    username: "truongphong02",
    email: "truongphong02@example.com",
    password: "mk123@",
    name: "Trưởng Phòng 02",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "TP0002",
    roles: ["Trưởng Phòng"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: true, write: true, delete: true },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: true,
  },
];
