exports.mock_users = [
  {
    username: "nhanvien01",
    email: "nhanvien01@example.com",
    password: "mk123@",
    name: "Nhân Viên 01",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0001",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien02",
    email: "nhanvien02@example.com",
    password: "mk123@",
    name: "Nhân Viên 02",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0002",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien03",
    email: "nhanvien03@example.com",
    password: "mk123@",
    name: "Nhân Viên 03",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0003",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien04",
    email: "nhanvien04@example.com",
    password: "mk123@",
    name: "Nhân Viên 04",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0004",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien05",
    email: "nhanvien05@example.com",
    password: "mk123@",
    name: "Nhân Viên 05",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0005",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien06",
    email: "nhanvien06@example.com",
    password: "mk123@",
    name: "Nhân Viên 06",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0006",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien07",
    email: "nhanvien07@example.com",
    password: "mk123@",
    name: "Nhân Viên 07",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0007",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "nhanvien08",
    email: "nhanvien08@example.com",
    password: "mk123@",
    name: "Nhân Viên 08",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "CS0008",
    roles: ["Nhân Viên"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: false, write: false, delete: false },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: false,
  },
  {
    username: "truongphong01",
    email: "truongphong01@example.com",
    password: "mk123@",
    name: "Trưởng Phòng 01",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "TP0001",
    roles: ["Trưởng Phòng"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: true, write: true, delete: true },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: true,
  },
  {
    username: "truongphong02",
    email: "truongphong02@example.com",
    password: "mk123@",
    name: "Trưởng Phòng 02",
    avatar: "/images/default-avatar.png",
    assignedUnit: "PC08",
    serviceNumber: "TP0002",
    roles: ["Trưởng Phòng"],
    permissions: {
      general: { read: true, write: true, delete: true },
      users: { read: true, write: true, delete: true },
      settings: { read: true, write: true, delete: true },
      records: { read: true, write: true, delete: true },
      reports: { read: true, write: true, delete: true },
    },
    isAdmin: true,
  },
];

exports.sample_record = {
  // plateNumber: "51A-12345", // unique
  color: "Vàng",
  // identificationNumber: "VIN000001", // uinque
  // engineNumber: "ENG000001", // uinque
  registrant: "Nguyen Van A",
  phone: "0901234567",
  email: "vana@example.com",
  address: "123 Đường Lê Lợi, Q1, TP.HCM",
  note: "Xe sử dụng hằng ngày",
  status: "processing",
};
exports.mock_records = [
  {
    plateNumber: "51A-12345",
    color: "Vàng",
    identificationNumber: "VIN000001",
    engineNumber: "ENG000001",
    registrant: "Nguyen Van A",
    phone: "0901234567",
    email: "vana@example.com",
    address: "123 Đường Lê Lợi, Q1, TP.HCM",
    note: "Xe sử dụng hằng ngày",
    status: "processing",
  },
  {
    plateNumber: "51B-67890",
    color: "Trắng",
    identificationNumber: "VIN000002",
    engineNumber: "ENG000002",
    registrant: "Tran Thi B",
    phone: "0912345678",
    email: "thib@example.com",
    address: "456 Trần Hưng Đạo, Q5, TP.HCM",
    note: "Xe công vụ",
    status: "archived",
  },
  {
    plateNumber: "59C-22222",
    color: "Trắng",
    identificationNumber: "VIN000003",
    engineNumber: "ENG000003",
    registrant: "Le Van C",
    phone: "0987654321",
    email: "le.c@example.com",
    address: "789 Nguyễn Trãi, Q10, TP.HCM",
    note: "Mới mua",
    status: "processing",
  },
  {
    plateNumber: "60D-33333",
    color: "Trắng",
    identificationNumber: "VIN000004",
    engineNumber: "ENG000004",
    registrant: "Pham Thi D",
    phone: "0977123456",
    email: "phamd@example.com",
    address: "12 Lê Văn Sỹ, Q3, TP.HCM",
    note: "Đã qua sử dụng",
    status: "archived",
  },
  {
    plateNumber: "61E-44444",
    color: "Trắng",
    identificationNumber: "VIN000005",
    engineNumber: "ENG000005",
    registrant: "Hoang Van E",
    phone: "0933123123",
    email: "hoange@example.com",
    address: "34 Phan Xích Long, Phú Nhuận",
    note: "Đăng kiểm định kỳ",
    status: "processing",
  },
  {
    plateNumber: "62F-55555",
    color: "Trắng",
    identificationNumber: "VIN000006",
    engineNumber: "ENG000006",
    registrant: "Dang Thi F",
    phone: "0966554433",
    email: "dangf@example.com",
    address: "101 Võ Thị Sáu, Q3",
    note: "",
    status: "archived",
  },
  {
    plateNumber: "63G-66666",
    color: "Trắng",
    identificationNumber: "VIN000007",
    engineNumber: "ENG000007",
    registrant: "Ngo Van G",
    phone: "0944112233",
    email: "ngog@example.com",
    address: "23 Nguyễn Thị Minh Khai, Q1",
    note: "Xe điện",
    status: "processing",
  },
  {
    plateNumber: "64H-77777",
    color: "Vàng",
    identificationNumber: "VIN000008",
    engineNumber: "ENG000008",
    registrant: "Bui Thi H",
    phone: "0922334455",
    email: "buih@example.com",
    address: "89 Pasteur, Q3",
    note: "Đăng ký mới",
    status: "archived",
  },
  {
    plateNumber: "65K-88888",
    color: "Vàng",
    identificationNumber: "VIN000009",
    engineNumber: "ENG000009",
    registrant: "Vo Van K",
    phone: "0909988776",
    email: "vok@example.com",
    address: "567 Lý Thái Tổ, Q10",
    note: "Xe du lịch",
    status: "processing",
  },
  {
    plateNumber: "66L-99999",
    color: "Vàng",
    identificationNumber: "VIN000010",
    engineNumber: "ENG000010",
    registrant: "Nguyen Thi L",
    phone: "0911223344",
    email: "nguyenl@example.com",
    address: "102 Hùng Vương, Q5",
    note: "Xe chở hàng",
    status: "archived",
  },
];

// prettier-ignore
exports.person_names = [
  "Nguyễn Văn An", "Trần Thị Bích", "Lê Văn Cường", "Phạm Thị Dung", 
  "Hoàng Minh Đức", "Võ Thị Hạnh", "Đặng Quốc Huy", "Bùi Thị Lan", 
  "Ngô Văn Long", "Dương Thị Mai", "Vũ Quang Minh", "Đỗ Thị Ngọc", 
  "Phan Văn Nam", "Lý Thị Nhung", "Huỳnh Quốc Phong", "Tô Thị Quỳnh", 
  "Cao Minh Sơn", "Trịnh Thị Thảo", "Lâm Thanh Tùng", "Mai Thị Vân", 
  "Hồ Văn Việt", "Đinh Thị Yến", "Châu Ngọc Ánh", "Kiều Hải Đăng", 
  "Tăng Thanh Hà", "Nguyễn Đình Vũ",
];
